//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace www.aquarella.com.pe.ws_clientedniruc {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.consultabata.com/", ConfigurationName="ws_clientedniruc.Cons_ClienteSoap")]
    public interface Cons_ClienteSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_update_cliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ws_update_cliente(string _ruc, string _nombres, string _apepat, string _apemat, string _telefono, string _email, string _tda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_update_cliente", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ws_update_clienteAsync(string _ruc, string _nombres, string _apepat, string _apemat, string _telefono, string _email, string _tda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_conscliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ws_conscliente(string _dniruc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_conscliente", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ws_consclienteAsync(string _dniruc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_persona_reniec", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ws_persona_reniec(string _dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_persona_reniec", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ws_persona_reniecAsync(string _dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_persona_sunat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ws_persona_sunat(string _ruc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_persona_sunat", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ws_persona_sunatAsync(string _ruc);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Cons_ClienteSoapChannel : www.aquarella.com.pe.ws_clientedniruc.Cons_ClienteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Cons_ClienteSoapClient : System.ServiceModel.ClientBase<www.aquarella.com.pe.ws_clientedniruc.Cons_ClienteSoap>, www.aquarella.com.pe.ws_clientedniruc.Cons_ClienteSoap {
        
        public Cons_ClienteSoapClient() {
        }
        
        public Cons_ClienteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Cons_ClienteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Cons_ClienteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Cons_ClienteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ws_update_cliente(string _ruc, string _nombres, string _apepat, string _apemat, string _telefono, string _email, string _tda) {
            return base.Channel.ws_update_cliente(_ruc, _nombres, _apepat, _apemat, _telefono, _email, _tda);
        }
        
        public System.Threading.Tasks.Task<string> ws_update_clienteAsync(string _ruc, string _nombres, string _apepat, string _apemat, string _telefono, string _email, string _tda) {
            return base.Channel.ws_update_clienteAsync(_ruc, _nombres, _apepat, _apemat, _telefono, _email, _tda);
        }
        
        public System.Data.DataTable ws_conscliente(string _dniruc) {
            return base.Channel.ws_conscliente(_dniruc);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ws_consclienteAsync(string _dniruc) {
            return base.Channel.ws_consclienteAsync(_dniruc);
        }
        
        public System.Data.DataTable ws_persona_reniec(string _dni) {
            return base.Channel.ws_persona_reniec(_dni);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ws_persona_reniecAsync(string _dni) {
            return base.Channel.ws_persona_reniecAsync(_dni);
        }
        
        public System.Data.DataTable ws_persona_sunat(string _ruc) {
            return base.Channel.ws_persona_sunat(_ruc);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ws_persona_sunatAsync(string _ruc) {
            return base.Channel.ws_persona_sunatAsync(_ruc);
        }
    }
}
